# Default image (https://hub.docker.com/_/ubuntu/)
image: ubuntu:latest

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -yqq
  - apt-get install -yqq openjdk-18-jdk ant junit5

# Build
build_game:
  stage: build
  script:
    - ant compile
    - ant jar

# Test
test_model:
  stage: test
  script:
    - ant test

# Documentation
pages:
  stage: deploy
  script:
    - ant javadoc
    - cp -r dist/javadoc/. public/
  artifacts:
    paths:
      - public
    expire_in: 7 day
  only:
    - master


